excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - RI/Resources/Rswift

disabled_rules: # rule identifiers to exclude from running
  - todo

identifier_name:
  min_length: 2